Feature/revenue 128 create rating district
Skillz-systems/revenue_hub pull request #183
Opened 2024-07-26 12:06 UTC by Highpriest26

My work

2024-07-31 14:26 UTC, Skillz-systems requested changes

2024-07-31 14:26 UTC, Skillz-systems commented on Frontend/src/Components/Settings/PropertyType/PropertyTypeModal.tsx
> +        alert('Property Type created successfully!');
replace alert with a snackbar or a toast

2024-07-31 14:26 UTC, Skillz-systems commented on Frontend/src/Components/Settings/PropertyUse/PropertyuseModal.tsx
> +        alert('Property Type created successfully!');
change alert to toast

2024-07-31 14:26 UTC, Skillz-systems commented on Frontend/src/Components/Settings/RatingDistrict/RatingDistrictModal.tsx
> +        alert('Rating District created successfully!');
change alert to toast

2024-07-31 14:26 UTC, Skillz-systems commented on Frontend/src/Components/Settings/Street/StreetModal.tsx
> +        alert('Street created successfully!');
change alert to toast

2024-08-27 23:58 UTC, kingsonly approved these changes

2024-08-27 23:59 UTC, Skillz-systems approved these changes

2024-08-28 00:02 UTC, closed without merging