Feature/revenue 17 view all properties
Skillz-systems/revenue_hub pull request #48
Opened 2024-05-16 20:52 UTC by Udosaint

2024-05-17 15:01 UTC, Skillz-systems requested changes
Make the change and get back to me

2024-05-17 15:01 UTC, Skillz-systems commented on Backend/app/Http/Resources/ShowPropertyResource.php
> +            //'penalty' => $this->penalty,
have in mind you would need to put the demand notice relationship and also the payment relationship

2024-05-17 15:16 UTC, Udosaint commented on Backend/app/Http/Resources/ShowPropertyResource.php
>              'street_name' => $this->street_name,
Done

2024-05-18 13:02 UTC, Skillz-systems approved these changes

2024-05-18 13:02 UTC, merged